### ISSUE TITLE
Team 3: Enhancing Questionnaire

### ISSUE THREAD

**Issue by LiuBrianna** [cornellh4i/OKB-hope#131]
### This is a **ONE WEEK** ticket. The first PR should be pushed on April 10th @10 PM and the revisions should be finished on April 12th @10 PM. 

Your tasks will be to edit the questionnaire to improve the flow. These tasks can be split up and are not chained. Right now, the onboarding questionnaire is finished but there are a few bugs and features that we want to fix to make the flow better. 

- [x] Create a new branch called `EnhanceQuestAndDisplayProf` and push this to the repo. 

**Task 1: Enhancing Questionnaire**
- [x] The onboarding questionnaire experiences formatting issues across different browsers and devices, leading to page bleeding and overlapping components.! We need to change the questionnaire to use flex boxes. The relevant files are located in `frontend/src/components/onboarding` and possible corresponding questionaries for patient: `frontend/src/components/patientQuestionnaire` and psych: `src/components/psychQuestionnaire`

What is a flex box? Here is an [article](https://medium.com/@devwares/how-to-use-tailwind-css-flex-a1fd8da339b6#:~:text=Flexbox%20is%20a%20model%20used,four%20properties%20available%20to%20it.) that explains it so well! 
![Example: Laptop Safari](https://github.com/cornellh4i/okb-hope/assets/140224336/55ef1745-f367-4ce3-b351-5f867cb72cdc)

**Task 2: Enhancing Patient Questionnaire**
- [x] Currently, in the patient questionnaire, users are able to list their concerns using a textbox. However,, we want to change this to be checkboxes with the following fields: `"My Relationships", "Addiction", "Suicidal Thoughts", "Family Distress", "Substance Abuse", "Academic Distress", "Social Anxiety", "Depression", "Other"`  In `frontend\src/components/patientQuestionnaire/HistoryQuestionnaire.tsx`update the frontend to reflect this change. There may be additional files that will now have errors because of this change.  _It it important that if the user checks `other`, they should be prompted to fill out a text field to describe what they mean._ 

**Here are some POSSIBLE resources to look into, but this is not a cut and paste solution nor does it fully encapsulate what we need to do**
- [https://jsfiddle.net/brL6gy7r/](https://jsfiddle.net/brL6gy7r/) <- If a checkbox is clicked a textfield is prompted.
- https://mui.com/material-ui/api/ 

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/7229a74b-69b6-4526-8807-b352054ad54e)

- [x]  We want to store the user's inputs regarding their concerns as a list of strings in the backend. Initially, we'll make these updates in the frontend\src\components\patientQuestionnaire\HistoryQuestionnaire.tsx file. Afterwards, we'll need to identify any other areas that require editing to ensure proper implementation.

**Task 3: Enhancing Psych Questionnaire**

- [x] Similar to task 2, we also want to edit the psych questionnaire to add an `other` field for a psych's current position. This should be reflected in `frontend/src/components/psychQuestionnaire/PositionLanguageQuestionnaire.tsx` and in the backend.

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/3b879a55-af37-4d4b-9a9b-8107a8d230c7)

- [x] Update the backend to ensure synchronization with the frontend changes. If the user selects `Other` and provides input in the text field, ensure that Firebase reflects this by updating the corresponding data in the `position` field. Please make sure to test this thoroughly!

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/067b7f8b-0955-4a96-8730-4e427c7ff379)
