### ISSUE TITLE
Team 4: (Week 1 of 2) download button + approved psych

### ISSUE THREAD

**Issue by LiuBrianna** [cornellh4i/OKB-hope#133]
### This is a **ONE WEEK** ticket. The first PR should be pushed on April 10th @10 PM and the revisions should be finished on April 12th @10 PM. 

Your tasks will be to match the [designs](https://www.figma.com/file/QZ0QibglxiI8UrFtSzclw0/OKB?type=design&node-id=4153-5990&mode=design&t=Eykx9HK9ZFFUEwXS-0) for the approve psych flow. 

- [x] Create a new branch call `ApprovePsych` and push this to the repo.
- [x] First, to see the admin side find your user accounts on the firebase and change your `userType` from `psych/patient` to `admin`.

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/bd2bbddb-009c-4cb0-b51e-ebf02a1d4b79)

When you now login, you should get to this new dashboard. 

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/c63420f6-408a-4a0c-a9ec-c33ae705507e)

Right now, all psych and patients are here, unsorted. We want to display some sort of indicator (orange circle) that a psychiatrists needs approval.

**Task 1: Create the warning icon appear**
- [x] Get the `warning` icon to show up for at least on person. The table being show is located in `frontend/src/components/filter/FilterUserTable.tsx` You can get the image for the warning icon by switching to Figma's dev mode.  
- [x] Get the `approved` icon (a green check mark) to show up for at least one person. Both icons do not need to show up at the same time. Just be able to get the icons to show up is enough.

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/796b6c64-6278-406e-a185-d74ca0a0fef7)

**Task 2: Creating the viewing page**
We want it such that if a psych is pressed then the admin should see the information regarding that specific psych. This is very similar to what is currently implemented for discover professionals page all located in `src/components/dashboard`. The difference is that we DO NOT want the booking information. 

- [x] In `frontend/src/components` add a folder called `admin` and in `frontend/src/pages/admin/[admin_id]`, add a page call `admin`
- [x] Update the table such that when a psych is clicked then the psych profile is shown. To do this, it should redirect them to a different page, much like how discover professional work. This should all be in the `admin` folder you created. 
You can look through the `frontend/src/components/psychiatrists/PsychiatristCardsListing.tsx` to how discover professional is currently implemented.
- [x] Create the orange warning symbol to show up. The image attached shows an orange triangle but for consistency, keep the orange circle. When the admin hovers over the symbol it will display `requires approval`

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/e800e16a-ef19-4e9b-9e38-a07f5999e3b3)

- [x] Replace the `edit profile` and `analytics` button with a button that says `download`.
- [x] We DO NOT want the 3 dots to the right. This hinders the flow.
- [x] Now we will create the `Would you like to approve this account` component. This is a blue component with text and two buttons in it for `No` and `Yes`

Here is a helpful resource to get the button to show up:
[https://v1.tailwindcss.com/components/buttons](https://v1.tailwindcss.com/components/buttons)

- [x] If the `Yes` button is pressed, then the orange icon should turn into the green icon and a green bar should appear saying that `<psych name>  is now approved`. 

Here is are some helpful resource:
- https://www.shecodes.io/athena/43700-how-to-handle-click-events-in-react-typescript

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/c4c8415d-1a53-48fd-95be-075366b3a06d)
