### ISSUE TITLE
Team 3:  Enforcing Requirements

### ISSUE THREAD

**Issue by LiuBrianna** [cornellh4i/OKB-hope#138]
**This is a 1 week sprint. The PR will be due Wednesday, April 17th @12am (to account for the late start). Revisions are due Friday, April 19th @12am.**

For this ticket, you will be enforcing requirements in the questionnaires and updating questionnaire fields. 

- [x] Create a branch called `EnforceReqs` and push to the repo.

### **Task #1: Required section for patient questionnaire**

In the current implementation, the patient questionnaire, last page, does not require the patients to fill these fields before the account creation. 

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/3bf27bfd-2094-4635-9931-338b5fd5cd22)

This does not seem proper UI flow, since we want the users to have filled out some information so that the psychiatrists can help them out. There is a similar implementation for the previous pages all implemented in `frontend/src/components/patientQuestionnaire`.

- [x] Make the above fields (in the picture) required before the account creation is finished on `frontend/src/components/patientQuestionnaire/HistoryQuestionnaire.tsx`.

### **Task #2: Language selection for patient questionnaire**

- [x] A smaller bug is that the checkboxes for "your preferred languages" is not shown when clicked. There is a similar implementation in the psych questionnaire, `frontend/src/components/psychQuestionnaire/AgeLanguageQuestionnaire.tsx` if you get stuck.

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/ac69cbaf-2161-4329-b466-2f23519580e1)

### **Task #3: Job Location for psych questionnaire**

Right now we have this implementation for psychs to choose their jobs.

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/62aac64b-ac72-41c5-af1c-2203abfbf872)

However, this causes the error with how we are showing psych cards. Such like this: 

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/fde932f7-e9a5-4bb4-894c-8c559750fb69)

- [x] To resolve this, include a required location section so psych can input their work location. 
- [x] Fix the capitalization for job titles so it is homogenous (we want all caps). In the above example, `psychiatrist` is not capital. 
- [x] Save this data to the `location` parameter in the database. Here is an example: 

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/82d3ddf5-b422-40d3-bcd1-b3ce16580e57)

### **Task #4: Patient Edit profile**

Right now, when you are a new patient (just made an account) and you want to edit your profile through `Edit Profile`, here is the page that you get brought to. 

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/6e237a27-d892-447f-9939-1a73c87071cc)

- [x] Add `(Required)` for fields that are required, which will be all the fields.

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/d610e5bd-7c0c-4443-aa2e-1586f74b9c95)

- [x] There is an issue with displaying `Have you spoken with your counselor before?`. It shows ages instead of `Yes` or `No`.
