### ISSUE TITLE
Team 4 (Week 2 - Backend): Implement upload/download backend and filter approved/unapproved psych.

### ISSUE THREAD

**Issue by LiuBrianna** [cornellh4i/OKB-hope#147]
Your tasks will be to implement the backend of [your previous ticket](https://github.com/orgs/cornellh4i/projects/5/views/1?pane=issue&itemId=58114662) in order to fully finish the admin side. (YAY WE ARE ALMOST DONE!)

You will be continuing to work on the same branch, `ApprovePsych`. 

**These tasks do not have to be worked in order. IN FACT, we recommend splitting up the tasks if possible.** 

### Task 1:  Implementing approved/unapproved psych

- [x] Add a new field for all psych accounts called `status` which will have two states `approved` and `pending`. `frontend/src/components/psychQuestionnaire/PsychQuestionnaire.tsx` currently is the location where information from the psych questionnaire is updated to the database. 
- [x] Update the firebase such that every new psych account's `status` is `pending`
- [x] In the admin state, display a yellow icon for psych accounts with a `pending` status.
- [x] Upon admin approval, update the `status` of the respective psych account to `approved`, altering the flow accordingly. This follows the figma designs
![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/c4ae6564-4504-4a3b-8d97-c235bda7b44e)
- [x] If the admin rejects a psychiatric account, delete their information from the firebase. 

Here is a helpful resource on how to tackle this deleting information: 
- [https://firebase.google.com/docs/firestore/manage-data/delete-data](https://firebase.google.com/docs/firestore/manage-data/delete-data)

- [x] Update the admin dashboard to have a green check mark for psych accounts with an approved status and a yellow icon for those with a pending status. You can refer back to the figma for the flow or ask your TL.

### Task 2: Implement backend for downloading button 

In the previous ticket, you created the download button. Now we will retrieve the information. 

- [ ] Right now, when a psychiatrist signs up, there is a place for them to upload a profile image. We will modify this field to allow psych to upload files such as their resume, certificates, etc. 
![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/667a8522-261b-47e9-90d8-56b3841719e1)
- [ ] Moving back to the admin side, we will implement the download button. The flow is that when the admin presses the button, the admin should be able to retrieve everything that the psych uploaded from the previous field. 

Here is a helpful resource: 
- [https://firebase.google.com/docs/storage/web/upload-files#web-namespaced-api](https://firebase.google.com/docs/storage/web/upload-files#web-namespaced-api)

### Task 3: Filter bar on Admin Dashboard

This is the final feature of the admin side. Currently, main admin dashboard contains two tabs: Clients and Psychiatrists. However, selecting each tab does not alter the displayed cards.

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/d0cbc99c-54f4-435b-b691-5d2803f4b4dd)

![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/b7f126ba-34c4-41e0-a73b-48b56250e496)

- [x] Update the admin dashboard to ensure that selecting the `Clients` tab displays only patient profiles, while selecting the `Psychiatrists` tab shows only psychiatrist profiles.
- [x] For the Psychiatrists tab, incorporate an extra filter for `status` by `approved` or `pending` and ensure its functionality. This filter should automatically sort the psychiatrist's based on the account creation time of psychiatrists. 
- [x] Right now, the filter bar on the admin dashboard has no functionality. Your job is to have this filter work! There is a similar filter that is used in the `discover professionals` page. I'd recommend looking at `frontend/src/pages/patient/[patient_id]/discover.tsx` to see how it currently filters data.
