### ISSUE TITLE
Team 3: Redo previous branch and continued enhancement

### ISSUE THREAD

**Issue by LiuBrianna** [cornellh4i/OKB-hope#149]
These changes should be added onto the previous branch that you worked on. 

**Task 1: Redo a previous ticket**

There was an issue with the previous ticket but we encountered an issue with API calls. 

- [x] Redo [this ticket](https://github.com/cornellh4i/okb-hope/issues/131) without causing an API key to be pushed. 

**Task 2:  Fix the number of days left on the appointment** 
This screenshot was taken on April 14, 2024. The first card should say "In 1 day" and the second card should say "In 2 days". But the days left is currently not properly calculated as shown below.

![Image](https://github.com/cornellh4i/okb-hope/assets/123599926/98c788fa-4cb7-44a6-ae9f-4db71abdc10c)

- [x] Fix the calculations for how appointments are created. The appointment card is created in `frontend/src/components/dashboard/AppointmentCard.tsx`

**Task 3: Patient edit profile**
Here is the edit profile page right now for patients:
![Image](https://github.com/cornellh4i/okb-hope/assets/140224336/8ec81e73-682a-469e-9ac1-667e670ca294)

- [x] Fix the concerns in Edit Patient Profile so that it's the same as the patient questionnaire (list of concerns). 

**Task 4: Psych Weekly Availability** 

- [x] To the psych questionnaire, add a field called `“What days of the week are you typically available?”`. This should be checkboxes. 
- [x] Updated the firebase to reflect these changes so it can save this field. Save the information as a list of strings for each day of the week.
- [x] Change the `Edit Profile` for psych to have a way to change their weekly availability.
- [x] Add a time availability if a person select a time and save it to the database. This helps removes the error currently in the database.
![image](https://github.com/cornellh4i/okb-hope/assets/140224336/8bca0f80-d874-4835-8960-9889729adecc)

- [x] Have the weekly availability filter work for the `Discover Professionals` page. 

**Task 5: Edit Locations** 

- [x] Now that psych are able to input their working locations. We also want psych to be able to edit their work location when they click `edit profile`

**Task 6: Matching questionnaire with edit profile** 

- [x] Completely match the psych questionnaire with edit profile for psych
- [x] Completely match the patient questionnaire with edit profile for patient

**Task 7: Continuous debug**

- [x] There are bugs that are mentioned in the slack. They are pinned.
